name: maintenance
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.1+22

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+1
  file_picker: ^5.2.0+1
  #  dio: ^5.3.2
  get: ^4.6.5
  #  typed_data: ^1.3.0
  #  xml:
  path_provider: ^2.0.14
  maps_launcher: ^2.2.0
  #  background_location: ^0.8.0
  #  open_file: ^3.2.1
  open_filex: ^4.3.2
  pdf: ^3.10.1
  #  flutter_icons: ^1.1.0
  material_design_icons_flutter: ^6.0.7096
  fluttericon: ^2.0.0
  #  connectivity: ^3.0.6
  #  fluttertoast: ^8.0.9
  cupertino_icons: ^1.0.5
  printing: ^5.10.3
  #  toast: ^0.1.5
  #  animated_dialog_box:
  #  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  hexcolor: ^3.0.1
  shared_preferences: ^2.1.0
  flutter_polyline_points: ^1.0.0
  permission_handler: ^10.2.0
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  #  geocoder: ^0.2.1
  #  geocoder2: ^1.1.2
  connectivity_plus: ^3.0.2
  sqflite: ^2.2.6
  path: ^1.8.2
  table_calendar: ^3.0.6
  geocoding: ^2.1.0
  #  get_mac_address: ^0.0.2
  #  flutter_map_tile_caching: ^8.0.0
  mapsforge_flutter: ^2.0.2
  #  mac_address: ^1.0.0
  pie_chart: ^5.3.2
  fl_chart: ^0.61.0
  intl: ^0.18.0
  workmanager: ^0.5.1
  synchronized: ^3.0.0+3
  #  device_info_plus: ^7.0.0
  google_fonts: ^4.0.3
  gallery_saver: ^2.3.2
  floating_overlay: ^1.2.1
  flutter_local_notifications: ^15.1.0+1
  step_progress_indicator: ^1.0.2
  cached_network_image: ^3.3.1
  flutter_share: ^2.0.0
  package_info_plus: ^4.0.2
  lecle_downloads_path_provider: ^0.0.2+8
  whatsapp_share: ^2.0.2
  go_router: 6.2.0
  flutter_barcode_scanner: ^2.0.0
  mailer: ^6.0.1
  flutter_3d_controller: ^1.3.0
  #--------------------------------

dev_dependencies:
  #  flutter_test:
  #    sdk: flutter
  pedantic: ^1.11.1
  build_runner: ^2.1.11


flutter:
  uses-material-design: true

  assets:
    - images/
    #    - images/render_themes/
    #    - images/icons/
    #    - assets/
#    - images/logo.jpg
#    - images/LocationPermission.jpg
#    - images/LITSalesBanner.jpg
#    - images/response.txt
#    - packages/mapsforge_flutter/assets/patterns/
#    - packages/mapsforge_flutter/assets/symbol/
#  fonts:
#    - family: Fredoka One
#      fonts:
#        - asset: fonts/FredokaOne-Regular.ttf
#        - asset: fonts/SourceSansPro-Regular.ttf
#        - asset: fonts/Roboto-Regular.ttf
